[theme]
base="dark"
primaryColor="#9b87f5"            # grape/lavender accent
backgroundColor="#0b0f1a"         # deep navy
secondaryBackgroundColor="#111827" # slate panel
textColor="#e6e6f0"
font="sans serif"
